version: '3.9'
services:
  webserver:
    build: .
    ports: 
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always
  
  redis: 
    image: redis:8.2.4-alpine3.22
    ports:
      - "6379"
    volumes:
      - ./redis_data:/data
    restart: always
